Cemre badges
swe574-spring23/SWE574 pull request #111
Opened 2023-04-23 17:42 UTC by cemrekut

create all badges

2023-04-24 11:11 UTC, sozkan4 approved these changes
Detailed design. Badge structure & logic needs to be updated accordingy.

2023-04-24 14:53 UTC, ceydaduzgec commented on spaces/templates/post_edit.html
> +
Why do we have the lines from 119-236? Can you please check this wrong duplication of code? @cemrekut

2023-04-24 14:54 UTC, ceydaduzgec requested changes

2023-04-24 14:54 UTC, ceydaduzgec commented on spaces/templates/post_edit.html
>  {% endblock %}
Why do we have the lines from 119-236? Can you please check this wrong duplication of code? @cemrekut

2023-05-05 16:59 UTC, ceydaduzgec commented on spaces/templates/post_edit.html
>  {% endblock %}
@cemrekut Could you solve this issue and change the title of the pull request in format of `DEV | Badges` so that we can merge this one plase?

2023-05-05 17:13 UTC, cemrekut commented on spaces/templates/post_edit.html
>  {% endblock %}
Actually i fixed it but still seems same.

2023-05-06 12:07 UTC, closed without merging