Generatedata ceyda - Fixing Mock data models
swe574-spring23/SWE574 pull request #113
Opened 2023-04-24 10:29 UTC by sozkan4

Description 
Mock data models added for 1 admin and 2 normal users for 4 different spaces.

2023-04-24 15:09 UTC, ceydaduzgec requested changes
Great start but we need some little things that should be fixed. Let me know if something is unclear. Also can you fix the title of the pull request?

2023-04-24 15:09 UTC, ceydaduzgec commented on core/management/generate_data.py
> +for space in spaces:
These should be inside of the handle function. Please correct this and push it again.
If you want to learn more about what we are doing here:
- https://simpleisbetterthancomplex.com/tutorial/2018/08/27/how-to-create-custom-django-management-commands.html
- https://docs.djangoproject.com/en/4.2/howto/custom-management-commands/

2023-04-24 15:09 UTC, ceydaduzgec commented on README.md
> +  `python manage.py generate_data.py`
I realized I wrote the `.py` extra. It should be `python manage.py generate_data`

2023-04-24 15:09 UTC, ceydaduzgec commented on core/management/generate_data.py
> +from django.core.management import BaseCommand
Also the file structure should be: `core/management/commands/generate_data.py` 
And `core`app should be included in `INSTALLED_APPS`Can you fix this as well?

2023-04-24 15:09 UTC, ceydaduzgec commented on core/management/generate_data.py
> +        email=fake.email(),
Fake library is not included in imports. You can import them here or can use UserFactory to generate random users here.

2023-04-24 15:09 UTC, ceydaduzgec commented on core/management/generate_data.py
> +()
This () is extra please delete this and also please use the linter or we cannot merge this pull request without successfully passing the linter check.

2023-04-27 21:30 UTC, sozkan4 commented
Hello Ceyda I fixed the code and test it working fine also fixed read me file. One concern here is maybe we need to update reuirements txt file for the faker? Thanks in advance.

2023-05-03 17:41 UTC, ceydaduzgec commented on core/management/commands/generate_data.py
> +    posts_data = [
After this line the code is not indented as previously. Could you add on more tab to the code below please?

2023-05-03 17:44 UTC, ceydaduzgec commented
> Hello Ceyda I fixed the code and test it working fine also fixed read me file. One concern here is maybe we need to update reuirements txt file for the faker? Thanks in advance.

Hey, great work thanks!  We don't need to add faker since we were already using it other files. Only thing is this command is not working properly.  Could you find out the issue here please? If you want I can help you with that.

![image](https://user-images.githubusercontent.com/37382270/236000748-695467e1-53d6-4ef5-8773-e8b67a0b67ce.png)

2023-05-07 12:21 UTC, sozkan4 commented
@ceydaduzgec I think the problem is about model filtering and I think I fix it. Could you please give it a try?

2023-05-07 18:43 UTC, ceydaduzgec commented
@sozkan4 Looks amazing thanks a lot!

2023-05-07 18:43 UTC, ceydaduzgec approved these changes

2023-05-07 18:44 UTC, merged