adding PostSearchTestCase
swe574-spring23/SWE574 pull request #123
Opened 2023-05-08 09:07 UTC by cemrekut

2023-05-08 15:28 UTC, MariaAsif135 reviewed
Thanks

2023-05-08 16:38 UTC, cemrekut commented
@MariaAsif135 hi, We had the same error recently, you were able to solve it, can you show it to me?

2023-05-23 17:55 UTC, cemrekut reviewed
@MariaAsif135 can you check

2023-05-23 18:07 UTC, ceydaduzgec requested changes

2023-05-23 18:07 UTC, ceydaduzgec commented on app_server/spaces/tests/tests.py
> +
Can you delete this line please?

2023-05-24 10:09 UTC, cemrekut commented on app_server/spaces/tests/tests.py
> +
fixed

2023-05-24 10:24 UTC, ceydaduzgec commented
Can you also fix linter issues, it is not passing them?

2023-05-24 11:20 UTC, cemrekut commented
> Can you also fix linter issues, it is not passing them?
@ceydaduzgec 
Unfortunately, it gives an error there because it has not been added to the recomendation and tag yet.

2023-05-24 11:29 UTC, ceydaduzgec commented
It isn't related to that. Can you run the pre-commit command on you local so that linter fixes the syntax errors?

2023-05-25 15:00 UTC, closed without merging